language: python
python: 2.7
sudo: false
os:
  - linux
env:
  global:
    - "PIP_DOWNLOAD_CACHE=$HOME/.pip-cache"
    # Temporary to get PR tests to pass
    - "ST2_REPO_BRANCH=register_content_fail_on_failure_flag"
  matrix:
    - "TASK=flake8"
    - "TASK=pylint"
    - "TASK=configs-check"
    - "TASK=metadata-check"
    - "TASK=packs-tests"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install --upgrade pip
script:
  - ./scripts/travis.sh
notifications:
  email:
    - eng@stackstorm.com
