---
# Used for auth test action
auth_test_action:
  token: ""

# Used for list channels
list_channels_action:
  token: ""
  exclude_archived: 0

# Used for list users action
list_users_action:
  token: ""

# Used for send invite action
send_invite_action:
  organization: ""
  token: ""
  set_active: false
  attempts: 1
  auto_join_channels:
    - C0123456

# Used for post message action
post_message_action:
  webhook_url: "https://hooks.slack.com/services/<replace me>"
  username: "my-bot"
  icon_emoji: ":panda_face:"

# Used for Slack sensor
sensor:
  token: ""
  strip_formatting: false
